package de.pilzscout.app.data.species

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Read-only species database shipped inside the "core" pack component.
 * The SQLite file is generated by tools/ from the exported Room schema (app/schemas), so
 * any change here requires bumping SpeciesDatabase.VERSION and rebuilding the pack.
 */
@Entity(
    tableName = "species",
    indices = [Index("model_class_index", unique = true), Index("genus"), Index("family")],
)
data class SpeciesEntity(
    @PrimaryKey val id: String,
    @ColumnInfo(name = "scientific_name") val scientificName: String,
    val binomial: String,
    val genus: String,
    @ColumnInfo(name = "specific_epithet") val specificEpithet: String,
    val family: String?,
    @ColumnInfo(name = "order_name") val orderName: String?,
    @ColumnInfo(name = "class_name") val className: String?,
    @ColumnInfo(name = "common_de") val commonDe: String?,
    @ColumnInfo(name = "common_en") val commonEn: String?,
    val poisonous: Int,
    @ColumnInfo(name = "gbif_key") val gbifKey: Long?,
    @ColumnInfo(name = "de_occurrences") val deOccurrences: Int,
    @ColumnInfo(name = "in_germany") val inGermany: Int,
    @ColumnInfo(name = "model_class_index") val modelClassIndex: Int,
    @ColumnInfo(name = "has_wiki_de") val hasWikiDe: Int,
    @ColumnInfo(name = "has_wiki_en") val hasWikiEn: Int,
    @ColumnInfo(name = "n_observations") val nObservations: Int,
)

/** Normalised search terms (lower-case, umlauts folded). kind: scientific | common_de | common_en | genus */
@Entity(tableName = "species_search", indices = [Index("species_id"), Index("text_norm")])
data class SpeciesSearchEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    @ColumnInfo(name = "species_id") val speciesId: String,
    @ColumnInfo(name = "text_norm") val textNorm: String,
    val kind: String,
)

@Entity(tableName = "trait", indices = [Index(value = ["species_id", "feature"])])
data class TraitEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    @ColumnInfo(name = "species_id") val speciesId: String,
    val feature: String,
    val lang: String,
    val text: String,
    @ColumnInfo(name = "value_key") val valueKey: String?,
    val basis: String,
    val source: String?,
)

@Entity(tableName = "species_stats")
data class SpeciesStatsEntity(
    @PrimaryKey @ColumnInfo(name = "species_id") val speciesId: String,
    @ColumnInfo(name = "habitats_json") val habitatsJson: String,
    @ColumnInfo(name = "substrates_json") val substratesJson: String,
    @ColumnInfo(name = "month_hist_json") val monthHistJson: String,
    @ColumnInfo(name = "regions_json") val regionsJson: String,
    @ColumnInfo(name = "n_obs") val nObs: Int,
    @ColumnInfo(name = "n_dna") val nDna: Int,
)

@Entity(tableName = "wiki_article", primaryKeys = ["species_id", "lang"])
data class WikiArticleEntity(
    @ColumnInfo(name = "species_id") val speciesId: String,
    val lang: String,
    val title: String,
    val url: String,
    @ColumnInfo(name = "revision_id") val revisionId: Long,
    val summary: String,
    val description: String?,
    @ColumnInfo(name = "thumb_file") val thumbFile: String?,
    @ColumnInfo(name = "sections_json") val sectionsJson: String,
    val license: String,
    @ColumnInfo(name = "retrieved_at") val retrievedAt: String,
)

@Entity(tableName = "fungitastic_observation", indices = [Index("species_id")])
data class FtObservationEntity(
    @PrimaryKey @ColumnInfo(name = "observation_id") val observationId: Long,
    @ColumnInfo(name = "species_id") val speciesId: String,
    @ColumnInfo(name = "event_date") val eventDate: String?,
    val month: Int?,
    val region: String?,
    val district: String?,
    val habitat: String?,
    val substrate: String?,
    @ColumnInfo(name = "meta_substrate") val metaSubstrate: String?,
    val lat: Double?,
    val lon: Double?,
    @ColumnInfo(name = "coord_uncert") val coordUncert: Double?,
    val split: String,
    @ColumnInfo(name = "dna_sequenced") val dnaSequenced: Int,
    @ColumnInfo(name = "biogeo_region") val biogeoRegion: String?,
    val elevation: Double?,
)

@Entity(tableName = "fungitastic_photo", indices = [Index("observation_id"), Index("species_id")])
data class FtPhotoEntity(
    @PrimaryKey val filename: String,
    @ColumnInfo(name = "observation_id") val observationId: Long,
    @ColumnInfo(name = "species_id") val speciesId: String,
    val caption: String?,
    @ColumnInfo(name = "has_mask") val hasMask: Int,
    @ColumnInfo(name = "thumb_file") val thumbFile: String?,
    @ColumnInfo(name = "hd_file") val hdFile: String?,
)
